### ISSUE TITLE
Add permissible license

### ISSUE THREAD

**Issue by RickSnyder** [dgryski/trifles#14]
I'm wondering if you'd be willing to add a permissible open source license to this repository, such as BSD, Apache 2.0, or MIT.  I am working on a project that uses code from this repo as a transitive dependency and this module is currently failing our license checks.  Any chance you'd be willing to add a license?

Thanks!

**Comment by dgryski** [comment]
Ok. I'm curious which piece you need?

**Comment by msross** [comment]
We have the same need.  The piece needed by us is the "leven" package, which is used by agnivade/levenshtein for testing.

**Comment by dgryski** [comment]
Added an MIT license to the top-level.

**Comment by msross** [comment]
Thank you!
